version: '3.8'
services:
  api:
    build:
      dockerfile: ./Dockerfile
      context: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/app/
    command: [ "sh", "-c", "sleep 20 && npm run start:dev" ]
